Improve Python 2.6 failure message.
Before:

    $ python2.6 -c 'import distutils644'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "distutils644.py", line 125
        with monkeypatch(os, 'listdir', os_listdir), \
                                                   ^
    SyntaxError: invalid syntax

After:

    $ python2.6 -c 'import distutils644'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "distutils644.py", line 47
        {0}  # Python >= 2.7 is required
          ^
    SyntaxError: invalid syntax